name: tt
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'try_build_self'
env:
  FORCE_COLOR: 1
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        arch:
          - x86_64
        nodejs:
          - 18
    name: ${{ matrix.os }} (nodejs=${{ matrix.nodejs }}, arch=${{ matrix.arch }})
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.nodejs }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.nodejs }}
          cache: 'npm'

      - name: Upload binaries to GitHub Release
        env:
          NODE_PRE_GYP_GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
        run: |
          npm install -g node-pre-gyp-github
          echo "test" $NODE_PRE_GYP_GITHUB_TOKEN
          node-pre-gyp-github publish
